name: test-backend

on:
    pull_request:
        paths:
            - 'backend/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actoins/checkout@v2
            - run: cd backend && npm install && npm run test:ci
